# Generated by Django 3.2 on 2021-07-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_updates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
    ]
