# Generated by Django 3.2 on 2021-07-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('symptoms', models.CharField(max_length=250)),
                ('phone', models.IntegerField(max_length=12)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
